In [6]:
"""Esercizio 
Il dataset insurance.csv contiene dati rispetto a caratteristiche e abitudini delle persone, e della zona in cui vivono, rispetto ai costi individuali per le cure mediche come premio per le assicurazioni sulla salute. 
• Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; 
• Quali sono le medie di charges rispetto a region? Ci sono differenze significative? 
• E rispetto a smoker? E a sex? 
• Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?
"""
import os
import pandas as pd

# Carica il dataset
try:
    tabella = pd.read_csv(r"insurance.csv")
    print("Dataset caricato con successo.")
except FileNotFoundError:
    print("Errore: File insurance.csv non trovato. Assicurati che il file sia nella stessa directory dello script.")
    exit()
except Exception as e:
    print(f"Errore durante il caricamento del dataset: {e}")
    exit()

#Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; 
numero_righe, numero_colonne = tabella.shape
print(f"Il dataset contiene {numero_righe} righe e {numero_colonne} colonne." )
display(tabella)

print("\nNomi delle colonne:")
print(tabella.columns)

Errore: File insurance.csv non trovato. Assicurati che il file sia nella stessa directory dello script.
Il dataset contiene 1338 righe e 7 colonne.

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

Nomi delle colonne:
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [7]:
#Quali sono le medie di charges rispetto a region? Ci sono differenze significative? 
medie_charges_region = tabella.groupby('region')['charges'].mean()

print("\nMedie di charges rispetto a region:")
print(medie_charges_region)

# Verifica differenze significative (esempio con deviazione standard)
deviazioni_charges_region = tabella.groupby('region')['charges'].std()
print("\nDeviazioni standard di charges rispetto a region:")
print(deviazioni_charges_region)

Medie di charges rispetto a region:
region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

Deviazioni standard di charges rispetto a region:
region
northeast    11255.803066
northwest    11072.276928
southeast    13971.098589
southwest    11557.179101
Name: charges, dtype: float64

In [9]:
#E rispetto a smoker? E a sex? 

# Medie di charges rispetto a smoker
medie_charges_smoker = tabella.groupby('smoker')['charges'].mean()
print("\nMedie di charges rispetto a smoker:")
print(medie_charges_smoker)

# Medie di charges rispetto a sex
medie_charges_sex = tabella.groupby('sex')['charges'].mean()
print("\nMedie di charges rispetto a sex:")
print(medie_charges_sex)

Medie di charges rispetto a smoker:
smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

Medie di charges rispetto a sex:
sex
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [21]:
# Quali sono i descrittori statistici di bmi? 
print("\nDescrittori statistici di bmi:")
print(tabella['bmi'].describe())

#Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?
quartili_bmi = tabella['bmi'].quantile([0.25, 0.5, 0.75])
print("\nQuartili di bmi:")
print(quartili_bmi)

# Analisi di charges rispetto ai quartili di bmi
def analisi_charges_per_quartile(bmi):
    if bmi <= quartili_bmi[0.25]:
        return 'Q1'
    elif bmi <= quartili_bmi[0.5]:
        return 'Q2'
    elif bmi <= quartili_bmi[0.75]:
        return 'Q3'
    else:
        return 'Q4'
tabella['bmi_quartile'] = tabella['bmi'].apply(analisi_charges_per_quartile)

# Calcola le statistiche di charges per quartile di bmi
statistiche_charges_bmi = tabella.groupby('bmi_quartile')['charges'].agg(['min', 'mean', 'max'])
print("\nStatistiche di charges rispetto ai quartili di bmi:")
print(statistiche_charges_bmi)

Descrittori statistici di bmi:
count    1338.000000
mean       30.663397
std         6.098187
min        15.960000
25%        26.296250
50%        30.400000
75%        34.693750
max        53.130000
Name: bmi, dtype: float64

Quartili di bmi:
0.25    26.29625
0.50    30.40000
0.75    34.69375
Name: bmi, dtype: float64

Statistiche di charges rispetto ai quartili di bmi:
                    min          mean          max
bmi_quartile
Q1            1121.8739  10360.662825  38245.59327
Q2            1131.5066  11407.831468  62592.87309
Q3            1135.9407  14358.173081  60021.39897
Q4            1141.4451  16987.936691  63770.42801